/**
 * keywords.js
 * -----------
 * Single source of truth for all keyword tooltips.
 *
 * USAGE IN HTML:
 *   <span class="kw" data-term="Command Test">Command Test</span>
 *
 * The visible text and the data-term can differ — useful for plurals,
 * mid-sentence capitalisation, or shorthand:
 *   <span class="kw" data-term="Order Points">OP</span>
 *
 * On DOMContentLoaded, every .kw[data-term] is resolved against KEYWORDS
 * and a tooltip span is injected inside it. If no matching term is found,
 * a console warning is emitted so broken references are caught early.
 */

const KEYWORDS = {
  "Action": {
    body: "Selected when a squad is activated. Dictates what the squad does for the phase. Three types: <strong>Instant</strong>, <strong>Prepare</strong>, and <strong>Reaction</strong>.",
  },
  "Activation Token": {
    body: "Placed next to a squad after it concludes its Action. A squad with an Activation Token cannot be selected again until the token is removed.",
  },
  "Aim": {
    body: "The To Hit threshold for <strong>Ranged Attacks</strong>. Penalties increase the threshold; bonuses decrease it. Can never be lower than 2+ (a roll of 1 always misses) but can exceed 7+ (impossible to hit).",
  },
  "Armour Rating": {
    body: "A measure of how protective a squad's armour is. Compare against the attacking weapon's Penetration Power to determine whether an armour save roll is needed.",
  },
  "Close-Combat Range": {
    body: "Within <strong>1″ horizontally</strong> (base-to-base) with a height difference of no more than <strong>5″</strong>.",
  },
  "Cohesion": {
    body: "A squad is Cohesive if every model is within 1″ of at least one other model in the squad and a continuous chain connects all models. Check after removing destroyed models.",
  },
  "Command Test": {
    body: "Roll <strong>3d6</strong> and compare the total to the squad's Leadership value. Equal to or above = <strong>pass</strong>. Below = <strong>fail</strong>.",
  },
  "Cover": {
    body: "A targeted squad has Cover if ≥50% of its models each have at least 25% of their model obscured by terrain. Grants a <strong>−1 to hit</strong> penalty against Ranged Attacks.",
  },
  "Endurance": {
    body: "The number of Wound Markers a model can sustain before being destroyed.",
  },
  "Hit Marker": {
    body: "Generated by a successful attack. Represented by a die set to the attack's Stopping Power value. Resolved during the Resolution Step — each one may wound a model.",
  },
  "Initiative Token": {
    body: "Held by the player who activates first in each phase. Passes to the other player at the end of each Strategic Phase.",
  },
  "Leadership": {
    body: "Used in <strong>Command Tests</strong>. Roll 3d6 and compare the result to this threshold. May never be increased past 18.",
  },
  "Line of Sight": {
    body: "Determined from the model's head (or geometric centre). At least <strong>25%</strong> of the target model or its base must be visible. Models see through their own squad but not through others.",
  },
  "Locked-in-Combat": {
    body: "A squad is Locked-in-Combat when any of its models are within Close-Combat Range of an opposing model.",
  },
  "Movement": {
    body: "How far a model can move in inches during a movement action. Cannot be reduced below <strong>0″</strong>. Each Wound Marker applies a stacking <strong>−2″</strong> penalty.",
  },
  "Opportunity Attack": {
    body: "An attack made outside a squad's normal activation. Carries an innate <strong>−2 to hit</strong> penalty due to its hasty nature.",
  },
  "Order Points": {
    body: "The resource spent to use Orders. Gain <strong>1 OP</strong> at the start of each round. Maximum pool is <strong>5 OP</strong>; excess is lost.",
  },
  "Penetration Power": {
    body: "A weapon stat representing its ability to punch through armour. Compare against the target's Armour Rating to determine whether hits automatically succeed or require an armour save roll.",
  },
  "Prowess": {
    body: "The To Hit threshold for <strong>Melee Attacks</strong>. Penalties increase the threshold; bonuses decrease it. Can never be lower than 2+ but can exceed 7+ (impossible to hit).",
  },
  "Routing": {
    body: "A squad that fails its Morale Command Test begins Routing. It may only take the <strong>Rout</strong> action and cannot score objectives until it passes a subsequent Command Test.",
  },
  "Stopping Power": {
    body: "A weapon (and Hit Marker) stat representing the force of impact. Compare against a model's Toughness to determine the wound roll threshold. Modified by the difference between Penetration Power and Armour Rating.",
  },
  "Toughness": {
    body: "A model stat representing resilience. Compare against incoming Stopping Power to determine the wound roll threshold on a 2d3.",
  },
  "Victory Points": {
    body: "The score used to determine match victory. Gained by completing Battlefield Objectives and Agendas. First player to reach <strong>10 VP</strong> wins.",
  },
  "Wound Marker": {
    body: "Placed on a model when a wound is successfully inflicted. Each marker applies <strong>−1 to Aim and Prowess</strong> and <strong>−2″ to Movement</strong>. When markers ≥ Endurance, the model is destroyed.",
  },
};

// ---------------------------------------------------------------------------
// Resolution
// ---------------------------------------------------------------------------

document.addEventListener("DOMContentLoaded", () => {
  document.querySelectorAll("span.kw[data-term]").forEach((el) => {
    const term = el.dataset.term;
    const kw = KEYWORDS[term];

    if (!kw) {
      console.warn(`[keywords.js] No definition found for data-term="${term}"`);
      return;
    }

    const tooltip = document.createElement("span");
    tooltip.className = "tooltip";
    tooltip.innerHTML = `<strong>${term}</strong><br>${kw.body}`;
    el.appendChild(tooltip);
  });
});